```{r}
library(keras)
library(devtools)
library(tensorflow)
library(tidyr)
library(ggplot2)
library(scales)
library(dplyr)
library(ramify)
library(yardstick)
library(cvms)
library(tibble)
```

```{r}
fashion_mnist <- dataset_fashion_mnist()
c(train_images, train_labels) %<-% fashion_mnist$train
c(test_images, test_labels) %<-% fashion_mnist$test

print(paste0("train size: ", dim(train_labels)))
print(paste0("test size: ", dim(test_labels)))

class_names = c('T-shirt/top',
                'Trouser',
                'Pullover',
                'Dress',
                'Coat', 
                'Sandal',
                'Shirt',
                'Sneaker',
                'Bag',
                'Ankle boot')
```

```{r}
image_1 <- as.data.frame(train_images[1, , ])
colnames(image_1) <- seq_len(ncol(image_1))
image_1$y <- seq_len(nrow(image_1))
image_1 <- gather(image_1, "x", "value", -y)
image_1$x <- as.integer(image_1$x)

ggplot(image_1, aes(x = x, y = y, fill = value)) +
  geom_tile() +
  scale_fill_gradient(low = "white", high = "black", na.value = NA) +
  scale_y_reverse() +
  theme_minimal() +
  theme(panel.grid = element_blank())   +
  theme(aspect.ratio = 1) +
  xlab("") +
  ylab("")
```




```{r}
MinMaxScale <- function(x, na.rm = TRUE) {
  return((x- min(x)) /(max(x)-min(x)))
}

train_images <- MinMaxScale(train_images)
test_images <- MinMaxScale(test_images)
```

```{r}
dev.new()
par(mfcol=c(5,5))
par(mar=c(0, 0, 1.5, 0), xaxs='i', yaxs='i')
for (i in 1:25) { 
  img <- train_images[i, , ]
  img <- t(apply(img, 2, rev)) 
  image(1:28, 1:28, img, col = gray((0:255)/255), xaxt = 'n', yaxt = 'n',
        main = paste(class_names[train_labels[i] + 1]))
}
```

```{r}
model <- keras_model_sequential()
model %>%
  layer_flatten(input_shape = c(28, 28)) %>%
  layer_dense(units = 500, activation = 'relu') %>%
  layer_dense(units = 200, activation = 'relu') %>%
  layer_dense(units = 100, activation = 'relu') %>%
  layer_dense(units = 10, activation = 'softmax')

model %>% compile(
  optimizer = 'adam', 
  loss = 'sparse_categorical_crossentropy',
  metrics = c('accuracy')
)

model %>% fit(train_images, train_labels, epochs = 5)
```

```{r}
score <- model %>% tensorflow::evaluate(test_images, test_labels, verbose = 0)
cat('Test loss:', score[1], "\n")
cat('Test accuracy:', score[2], "\n")
```

```{r}
predictions <- model %>% predict(test_images)
pred_labels <- argmax(predictions, rows = TRUE) - 1
```

```{r}
par(mfcol=c(5,5))
par(mar=c(0, 0, 1.5, 0), xaxs='i', yaxs='i')
for (i in 1:25) { 
  img <- test_images[i, , ]
  img <- t(apply(img, 2, rev)) 
  # subtract 1 as labels go from 0 to 9
  predicted_label <- which.max(predictions[i, ]) - 1
  true_label <- test_labels[i]
  if (predicted_label == true_label) {
    color <- '#008800' 
  } else {
    color <- '#bb0000'
  }
  image(1:28, 1:28, img, col = gray((0:255)/255), xaxt = 'n', yaxt = 'n',
        main = paste0(class_names[predicted_label + 1], " (",
                      class_names[true_label + 1], ")"),
        col.main = color)
}
```



```{r}
truelabels <- test_labels+1
truelabels <- factor((class_names[truelabels]))
predlabels <- pred_labels+1
predlabels <- factor((class_names[predlabels]))
df <- tibble(truelabels,predlabels)
cm <- confusion_matrix(targets = df$truelabels,predictions = df$predlabels)

dev.new()
plot_confusion_matrix(cm$`Confusion Matrix`[[1]],
                      add_normalized = FALSE,
                      add_col_percentages = FALSE,
                      add_row_percentages = FALSE,
                      diag_percentages_only = FALSE,
                      add_sums = TRUE,
                      palette = "Greens",
                      theme_fn = ggplot2::theme_light)
```


